### ISSUE TITLE
Ruby 2.x compatibility

### ISSUE THREAD

**Issue by vais** [SKAhack/net-http-uploadprogress#1]
@SKAhack does this work with Ruby 2.0.0 and up? Looks like the code in net/http library has changed since this gem was written. Do you have any alternatives or suggestions on how to get upload progress with net/http on modern Ruby?

**Comment by skahack** [comment]
@vais 

> Do you have any alternatives or suggestions on how to get upload progress with net/http on modern Ruby?

Umm... I don't know.

**Comment by vais** [comment]
@SKAhack I finally figured out a way to get upload progress to work for ruby 2.x, but it is a completely different approach from this gem's monkey-patching approach for ruby 1.x. Basically, in ruby 2.x net/http uses `IO.copy_stream`, which accepts any object that implements `readpartial`. So I wrap my real io in a fake io object that implements `readpartial`, which updates an internal progress counter, then delegates to the real io's `readpartial` method.

Are you interested in updating your gem for ruby 2? Would it support both ruby 1.x and 2.x? I would prefer to contribute to this gem instead of releasing a new gem to do the same thing for ruby 2, but I am not sure how to do this.

**Comment by skahack** [comment]
@vais 
If you send pull-request to this repo, I will update this gem :+1: 

> Would it support both ruby 1.x and 2.x?

I think support the only ruby 2.x. I don't know your approach because I don't read ruby 2.x code yet, but I will read it later.

**Comment by vais** [comment]
@SKAhack just sent you a pull request, [check it out](https://github.com/SKAhack/net-http-uploadprogress/pull/2) and let me know what you think!

**Comment by skahack** [comment]
@vais 
Version bumped. https://rubygems.org/gems/net-http-uploadprogress
Thanks again.
